config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'


  get '/dashboard', to: 'kkmembers#dashboard', as: 'dashboard'
  get '/kkmembers', to: 'kkmembers#index', as: 'kkmembers'
  get '/kkmember/show/:id', to: 'kkmembers#show', as: 'kkmember_show'
  get '/kkmembers/new', to: 'kkmembers#new', as: 'new_kkmember'
  post '/kkmember/create', to: 'kkmembers#create', as: 'add_kkmember'
  get '/kkmembers/edit/:id', to: 'kkmembers#edit', as: 'edit_kkmember'
  patch '/kkmembers/update/:id', to: 'kkmembers#update', as: 'update_kkmember'
  delete '/kkmembers/destroy/:id', to: 'kkmembers#destroy', as: 'destroy_kkmember'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/show_purok', to: 'kkmembers#purok', as: 'purok'
  post '/kkmembers/purok/create', to: 'kkmembers#create_purok', as: 'add_purok'
  delete '/kkmembers/purok/destroy/:id', to: 'kkmembers#destroy_purok', as: 'destroy_purok'
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/educationbg.rb
class Educationbg < ApplicationRecord  
end

app/models/familybg.rb
class Familybg < ApplicationRecord

end

app/models/healthinfo.rb
class Healthinfo < ApplicationRecord

end

app/models/kkmember.rb
class Kkmember < ApplicationRecord
   belongs_to :personalinfo, dependent: :destroy
   belongs_to :educationbg, dependent: :destroy
   belongs_to :familybg, dependent: :destroy
   belongs_to :healthinfo, dependent: :destroy
   belongs_to :workbg, dependent: :destroy
   accepts_nested_attributes_for :personalinfo, :educationbg, :familybg, :healthinfo, :workbg
  end

app/models/personalinfo.rb
class Personalinfo < ApplicationRecord
end

app/models/purok.rb
class Purok < ApplicationRecord
end

app/models/workbg.rb
class Workbg < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :admin_logged_in?
  
    def admin_logged_in?
      !!session[:admin_id]
    end
  
    # Ensure that admin is logged in for certain actions
    def require_admin_logged_in
      redirect_to login_path unless admin_logged_in?
    end
  end
  

app/controllers/kkmembers_controller.rb
class KkmembersController < ApplicationController
  before_action :set_kkmember, only: [:edit, :update, :show, :destroy]
  before_action :require_admin_logged_in, except: [:new, :create]
  before_action :set_purok, only: [:destroy_purok]
  before_action :set_puroksall, only: [:purok, :new, :dashboard, :create]
  def index
    @kkmembers = Kkmember.includes(:personalinfo, :educationbg, :familybg, :healthinfo, :workbg).all
  end

  def dashboard
    @kkmembers_count = Kkmember.count
    @registered = Kkmember.joins(:personalinfo).where(personalinfos: { registeredvoter: "Yes" }).count
    @notregistered = Kkmember.joins(:personalinfo).where(personalinfos: { registeredvoter: "No" }).count
  
    @purok_populations = {}

    @puroks.each do |purok|
      purok_population = Kkmember.joins(:personalinfo).where(personalinfos: { purok: purok.purokname }).count
      @purok_populations[purok.purokname] = {
        population: purok_population,
        registered: Kkmember.joins(:personalinfo).where(personalinfos: { purok: purok.purokname, registeredvoter: "Yes" }).count,
        not_registered: Kkmember.joins(:personalinfo).where(personalinfos: { purok: purok.purokname, registeredvoter: "No" }).count
      }
    end
  end

  def show
  end

  def new
    @kkmember = Kkmember.new
    
  end

  def create
    @kkmember = Kkmember.new(kkmember_params)
    
    if @kkmember.save
      redirect_to kkmembers_path, notice: 'KK Member was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @kkmember.update(kkmember_params)
      redirect_to kkmembers_path, notice: 'KK Member was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @kkmember.destroy
    redirect_to kkmembers_path, notice: 'KK Member was successfully destroyed.'
  end


  # Puroks Area

  def purok
  end

  def create_purok
    purok_name = purok_params[:purokname]
    existing_purok = Purok.where('lower(purokname) = ?', purok_name.downcase).first

    if existing_purok
      flash[:alert] = 'Purok already exists.'
      redirect_to purok_path
    else
      @purok = Purok.new(purok_params)
      if @purok.save
        redirect_to purok_path, notice: 'Purok was successfully created.'
      else
        render :show_purok
      end
    end
  end

  def destroy_purok
    @purok.destroy
    flash[:alert] = 'Purok was successfully destroyed.'
    redirect_to purok_path
  end



  private

  def set_kkmember
    @kkmember = Kkmember.find(params[:id])
  end

  def kkmember_params
    params.require(:kkmember).permit(
      personalinfo_attributes: [
        :id, :lastname, :firstname, :middlename, :age, :sex, :birthdate, 
        :civilstatus, :contactno, :emailaddress, :purok, :address, 
        :nationality, :registeredvoter, :organization
      ],
      educationbg_attributes: [
        :id, :hea, :elementary, :highschool, :college, :course, 
        :educationstatus, :ifoutofschool
      ],
      workbg_attributes: [
        :id, :work, :agency
      ],
      healthinfo_attributes: [
        :id, :disabilities, :medicalcondition
      ],
      familybg_attributes: [
        :id, :father, :fatherwork, :solofather, :mother, :motherwork, 
        :solomother, :familymemberno, :bother, :sister
      ]
    )
  end

  def require_admin_logged_in
    redirect_to login_path unless admin_logged_in?
  end

  def set_purok
    @purok = Purok.find(params[:id])
  end

  def purok_params
    params.require(:purok).permit(:purokname)
  end

  def set_puroksall
    @puroks = Purok.all
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to dashboard_path if admin_logged_in?
  end

  def create
    if params[:session].present? && params[:session][:username].present? && params[:session][:password].present?
      admin = Admin.find_by(username: params[:session][:username])

      if admin && admin.authenticate(params[:session][:password])
        session[:admin_id] = admin.id
        flash[:notice] = 'Successfully logged in'
        redirect_to dashboard_path and return
      end
    end

    flash.now[:error] = 'Invalid username/password combination'
    render 'new'
  end

  def destroy
    session.delete(:admin_id)
    flash[:notice] = 'Successfully logged out'
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kkmembers_helper.rb
module KkmembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/kkmembers/dashboard.html.erb
<style>
  .btn-round {
    border-radius: 50px; /* Makes the button round */
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-success" href="/dashboard">KKRIS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "KK Members", kkmembers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Purok", purok_path, class: "nav-link" %>
      </li>
    </ul>
    <% if admin_logged_in? %>
      <% admin = Admin.find_by(id: session[:admin_id]) %>
      <% if admin %>
        <span class="navbar-text mr-3">
          Logged in as <%= admin.username %>
        </span>
        <%= form_with(url: logout_path, method: :delete, class: "form-inline") do |form| %>
          <%= form.submit "Logout", class: "btn btn-outline-light bg-danger hover-light btn-round" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</nav>

<% flash.each do |type, msg| %>
  <div class="flash-message flash-<%= type == 'notice' ? 'notice' : 'alert' %>" style="margin-bottom: 1rem; padding: 0.75rem; border-radius: 0.25rem; color: #fff; background-color: <%= type == 'notice' ? '#4caf50' : '#f44336' %>;">
    <%= msg %>
  </div>
<% end %>

<div class="container custom-font">
  <h1 class="mt-4 mb-4 text-center">Dashboard</h1>

  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4 bg-success text-white">
        <div class="card-body py-5 text-center">
          <h5 class="card-title"><i class="fas fa-users"></i> KK Members</h5>
          <p class="card-text"><%= @kkmembers_count %></p>
           <!--<%= link_to "View", kkmembers_path, class: "btn btn-primary mt-2 btn-round" %>  -->
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4 bg-primary text-white">
        <div class="card-body py-5 text-center">
          <h5 class="card-title"><i class="fas fa-users"></i> Registered Voters</h5>
          <p class="card-text"><%= @registered %></p>
         <!--  <%= link_to "View", kkmembers_path, class: "btn btn-danger mt-2 btn-round" %>  -->
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4 bg-danger text-white">
        <div class="card-body py-5 text-center">
          <h5 class="card-title"><i class="fas fa-users"></i> Not Registered Voters</h5>
          <p class="card-text"><%= @notregistered %></p>
         <!-- <%= link_to "View", kkmembers_path, class: "btn btn-success mt-2 btn-round" %> -->
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
  <% @puroks.each do |purok| %>
    <div class="col-md-4">
      <div class="card mb-4" style="background-color: #FBAB7E; background-image: linear-gradient(62deg, #FBAB7E 0%, #F7CE68 100%);">
        <div class="card-body py-5 text-center text-danger">
          <h5 class="card-title">Purok <%= purok.purokname %>:</h5>
          <p class="card-text">Population: <%= @purok_populations[purok.purokname][:population] %></p>
          <p class="card-text">Registered: <%= @purok_populations[purok.purokname][:registered] %></p>
          <p class="card-text">Not Registered: <%= @purok_populations[purok.purokname][:not_registered] %> </p>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/kkmembers/index.html.erb
<style>
  .btn-round {
    border-radius: 50px; /* Makes the button round */
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-success" href="/dashboard">KKRIS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "KK Members", kkmembers_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Purok", purok_path, class: "nav-link" %>
      </li>
    </ul>
    <% if admin_logged_in? %>
      <% admin = Admin.find_by(id: session[:admin_id]) %>
      <% if admin %>
        <span class="navbar-text mr-3">
          Logged in as <%= admin.username %>
        </span>
        <%= form_with(url: logout_path, method: :delete, class: "form-inline") do |form| %>
          <%= form.submit "Logout", class: "btn btn-outline-light bg-danger hover-light btn-round" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</nav>

<div class="container ">
<% flash.each do |type, msg| %>
  <div class="flash-message flash-<%= type == 'notice' ? 'notice' : 'alert' %>" style="margin-bottom: 1rem; padding: 0.75rem; border-radius: 0.25rem; color: #fff; background-color: <%= type == 'notice' ? '#4caf50' : '#f44336' %>;">
    <%= msg %>
  </div>
<% end %>

  </div>
<div class="container custom-font">
  <h1 class="mt-4 mb-5 text-center">KK Members Record Information System</h1>
  


  <%= link_to "Add KK Member", new_kkmember_path, class: "btn btn-primary mb-3 " %>
  
  
  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Age</th>
        <th>Purok</th>
        <th>Registered Voters</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @kkmembers.each_with_index do |kkmember, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= kkmember.personalinfo.lastname %></td>
          <td><%= kkmember.personalinfo.firstname %></td>
          <td><%= kkmember.personalinfo.middlename %></td>
          <td><%= kkmember.personalinfo.age %></td>
          <td><%= kkmember.personalinfo.purok %></td>
          <td><%= kkmember.personalinfo.registeredvoter %></td>
          <td>
            <%= link_to "View", kkmember_show_path(kkmember), class: "btn btn-primary btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/kkmembers/purok.html.erb
<style>
  .btn-round {
    border-radius: 50px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-success" href="/dashboard">KKRIS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "KK Members", kkmembers_path, class: "nav-link" %>
      </li>
       <li class="nav-item active">
        <%= link_to "Purok", purok_path, class: "nav-link" %>
      </li>
    </ul>
    <% if admin_logged_in? %>
      <% admin = Admin.find_by(id: session[:admin_id]) %>
      <% if admin %>
        <span class="navbar-text mr-3">
          Logged in as <%= admin.username %>
        </span>
        <%= form_with(url: logout_path, method: :delete, class: "form-inline") do |form| %>
          <%= form.submit "Logout", class: "btn btn-outline-light bg-danger hover-light btn-round" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</nav>
<div class="container custom-font">
  <h1 class="mt-4 mb-4">Purok Management</h1>

  <% flash.each do |type, msg| %>
  <div class="flash-message flash-<%= type == 'notice' ? 'notice' : 'alert' %>" style="margin-bottom: 1rem; padding: 0.75rem; border-radius: 0.25rem; color: #fff; background-color: <%= type == 'notice' ? '#4caf50' : '#f44336' %>;">
    <%= msg %>
   </div>
 <% end %>

 <div class="container">
  <h1>Add Purok</h1>
  <form action="<%= add_purok_path %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="input-group mb-3 col-lg-3">
      <input type="text" id="purokname" name="purok[purokname]" class="form-control" placeholder="Purok Name">
      <div class="input-group-append">
        <button type="submit" class="btn btn-primary ">Add</button>
      </div>
    </div>
  </form>
</div>

  

  <h2>Puroks</h2>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>ID</th>
        <th>Purok Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @puroks.each_with_index do |purok, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= purok.id %></td>
          <td><%= purok.purokname %></td>
          <td>
            <form action="<%= destroy_purok_path(purok) %>" method="post">
                <input type="hidden" name="_method" value="delete">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <button type="submit" class="btn btn-danger">Delete</button>
              </form>
              
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/kkmembers/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-success" href="/dashboard">KKRIS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "KK Members", kkmembers_path, class: "nav-link" %>
      </li>
    </ul>
    <% if admin_logged_in? %>
  <% admin = Admin.find_by(id: session[:admin_id]) %>
  <% if admin %>
    <span class="navbar-text mr-3">
      Logged in as <%= admin.username %>
    </span>
    <%= form_with(url: logout_path, method: :delete, class: "form-inline") do |form| %>
      <%= form.submit "Logout", class: "btn btn-outline-light bg-danger hover-light" %>
    <% end %>
  <% end %>
<% end %>
  </div>
</nav>
 
<div class="container custom-font">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card mt-5">
        <div class="card-body">
          <a href="/kkmembers" class="btn btn-danger btn-sm custom-btn float-right">X</a>
          <h1 class="card-title mb-5 text-center">KK Member Details</h1>

          <div class="row">
            <div class="col-md-6">
              <h3 class="text-primary mb-3">Personal Information</h3>
              <ul class="list-group">
                <li class="list-group-item"><strong>Last Name:</strong> <%= @kkmember.personalinfo.lastname %></li>
                <li class="list-group-item"><strong>First Name:</strong> <%= @kkmember.personalinfo.firstname %></li>
                <li class="list-group-item"><strong>Middle Name:</strong> <%= @kkmember.personalinfo.middlename %></li>
                <li class="list-group-item"><strong>Age:</strong> <%= @kkmember.personalinfo.age %></li>
                <li class="list-group-item"><strong>Sex:</strong> <%= @kkmember.personalinfo.sex %></li>
                <li class="list-group-item"><strong>Registered Voters:</strong> <%= @kkmember.personalinfo.registeredvoter %></li>
                <li class="list-group-item"><strong>Purok:</strong> <%= @kkmember.personalinfo.purok %></li>
                <li class="list-group-item"><strong>Birthdate:</strong> <%= @kkmember.personalinfo.birthdate %></li>
                <li class="list-group-item"><strong>Civil Status:</strong> <%= @kkmember.personalinfo.civilstatus %></li>
                <li class="list-group-item"><strong>Contact Number:</strong> <%= @kkmember.personalinfo.contactno %></li>
                <li class="list-group-item"><strong>Email Address:</strong> <%= @kkmember.personalinfo.emailaddress %></li>
                <li class="list-group-item"><strong>Address:</strong> <%= @kkmember.personalinfo.address %></li>
                <li class="list-group-item"><strong>Nationality:</strong> <%= @kkmember.personalinfo.nationality %></li>
                <li class="list-group-item"><strong>Organization:</strong> <%= @kkmember.personalinfo.organization %></li>
              </ul>
            </div>
            <div class="col-md-6">
              <h3 class="text-primary mb-3">Educational Background</h3>
              <ul class="list-group">
                <li class="list-group-item"><strong>HEA:</strong> <%= @kkmember.educationbg.hea %></li>
                <li class="list-group-item"><strong>Elementary:</strong> <%= @kkmember.educationbg.elementary %></li>
                <li class="list-group-item"><strong>Highschool:</strong> <%= @kkmember.educationbg.highschool %></li>
                <li class="list-group-item"><strong>College:</strong> <%= @kkmember.educationbg.college %></li>
                <li class="list-group-item"><strong>Course:</strong> <%= @kkmember.educationbg.course %></li>
                <li class="list-group-item"><strong>Educ. Status:</strong> <%= @kkmember.educationbg.educationstatus %></li>
                <li class="list-group-item"><strong>If Out of School:</strong> <%= @kkmember.educationbg.ifoutofschool %></li>
              </ul>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-6">
              <h3 class="text-primary mb-3">Work Background</h3>
              <ul class="list-group">
                <li class="list-group-item"><strong>Work:</strong> <%= @kkmember.workbg.work %></li>
              </ul>
              <ul class="list-group">
                <li class="list-group-item"><strong>Agency:</strong> <%= @kkmember.workbg.agency %></li>
              </ul>
            </div>
            <div class="col-md-6">
              <h3 class="text-primary mb-3">Health Information</h3>
              <ul class="list-group">
                <li class="list-group-item"><strong>Disabilities:</strong> <%= @kkmember.healthinfo.disabilities %></li>
                <li class="list-group-item"><strong>Medical Condition:</strong> <%= @kkmember.healthinfo.medicalcondition %></li>
              </ul>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-6">
              <h3 class="text-primary mb-3">Family Background</h3>
              <ul class="list-group">
                <li class="list-group-item"><strong>Father's Name:</strong> <%= @kkmember.familybg.father %></li>
                <li class="list-group-item"><strong>Father's Work:</strong> <%= @kkmember.familybg.fatherwork %></li>
                <li class="list-group-item"><strong>Solo Father:</strong> <%= @kkmember.familybg.solofather %></li>
                <li class="list-group-item"><strong>Mother's Name:</strong> <%= @kkmember.familybg.mother %></li>
                <li class="list-group-item"><strong>Mother's Work:</strong> <%= @kkmember.familybg.motherwork %></li>
                <li class="list-group-item"><strong>Solo Mother:</strong> <%= @kkmember.familybg.solomother %></li>
                <li class="list-group-item"><strong>No. of Family Members:</strong> <%= @kkmember.familybg.familymemberno %></li>
                <li class="list-group-item"><strong>Brother:</strong> <%= @kkmember.familybg.bother %></li>
                <li class="list-group-item"><strong>Sister:</strong> <%= @kkmember.familybg.sister %></li>
              </ul>
            </div>
          </div>

          <div class="row mt-4">
            <div class="col-md-12 text-right">
              <%= link_to "Edit", edit_kkmember_path(@kkmember), class: "btn btn-primary" %>
              <%= form_tag destroy_kkmember_path(@kkmember), method: :delete do %>
                <%= submit_tag "Delete", class: "btn btn-danger ml-2" %>
              <% end %>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kkris</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    
    
    
      <%= yield %>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
    <script>
      // Function to hide flash message after 3 seconds
      setTimeout(function() {
        var flashMessage = document.querySelector('.flash-message');
        if (flashMessage) {
          flashMessage.style.transition = 'opacity 0.5s ease-out';
          flashMessage.style.opacity = '0';
          setTimeout(function() {
            flashMessage.style.display = 'none';
          }, 500); // Wait for the fade-out transition to complete
        }
      }, 3000); // 3000ms = 3 seconds
    </script>
  
  </body>
</html>